version: 0.2

phases:
  install:
    commands:
      - echo 'Install phase has started'
      - yum update -y
      - yum install -y java-17-amazon-corretto-devel
      - yum install -y maven
    finally:
      - echo 'Install phase is over'
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain gallery-company --domain-owner 809008733763 --region eu-central-1 --query authorizationToken --output text`
  build:
    commands:
      - echo 'Build phase has started'
      - mvn clean install -DskipTests=true
    finally:
      - echo 'Build phase is over'
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - target/gallery-0.0.1-SNAPSHOT.jar
    - application-start.sh
    - application-stop.sh
    - health_check.sh
    - appspec.yml
    - .aws/amazon-cloudwatch-agent.json
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'