version = 0.1
[default.deploy.parameters]
stack_name = "gallery-api"
resolve_s3 = true
s3_prefix = "gallery-api"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "S3ImagesBucketName=\"gallery-files-alexstk\""
image_repositories = []